### ISSUE TITLE
error Can't parse file 'system/extensions/csv.php'!

### ISSUE THREAD

**Issue by JetGum** [schulle4u/yellow-extensions-schulle4u#35]
Hi @schulle4u,

I run into a problem with csv.php. Tried to reproduce on a fresh Yellow install, and I get the same errors:

```
2022-11-20 07:23:59 info Install Datenstrom Yellow 0.8.21, PHP 7.4.3, Built-in 7.4.3, Linux
2022-11-20 07:23:59 info Install extension 'Update 0.8.91'
2022-11-20 07:23:59 info Install extension 'Command 0.8.45'
2022-11-20 07:23:59 info Install extension 'Core 0.8.102'
2022-11-20 07:23:59 info Install extension 'Edit 0.8.71'
2022-11-20 07:23:59 info Install extension 'Image 0.8.18'
2022-11-20 07:23:59 info Install extension 'Markdown 0.8.24'
2022-11-20 07:23:59 info Install extension 'Meta 0.8.16'
2022-11-20 07:23:59 info Install extension 'Serve 0.8.22'
2022-11-20 07:23:59 info Install extension 'Stockholm 0.8.14'
2022-11-20 07:23:59 info Install extension 'English 0.8.42'
2022-11-20 07:23:59 info Install extension 'German 0.8.42'
2022-11-20 07:23:59 info Install extension 'Swedish 0.8.42'
2022-11-20 07:24:14 info Add user 'Test'
2022-11-20 07:24:36 info Install extension 'Csv 0.8.16'
2022-11-20 07:26:30 error Can't parse file 'system/extensions/csv.php'!
2022-11-20 07:27:27 error Can't parse file 'system/extensions/csv.php'!
2022-11-20 07:27:34 error Can't parse file 'system/extensions/csv.php'!
2022-11-20 07:27:56 error Can't parse file 'system/extensions/csv.php'!
```

This is the frontend error message:

`Fatal error: Uncaught Error: Call to undefined method YellowToolbox::normaliseData() in /mnt/c/htdocs/yellow-master/system/extensions/csv.php:88 Stack trace: #0 /mnt/c/htdocs/yellow-master/system/extensions/csv.php(26): YellowCsv->getCsvHtml() #1 /mnt/c/htdocs/yellow-master/system/extensions/core.php(2983): YellowCsv->onParseContentShortcut() #2 /mnt/c/htdocs/yellow-master/system/extensions/markdown.php(3895): YellowPage->parseContentShortcut() #3 [internal function]: YellowMarkdownParser->_doAutoLinks_shortcutInline_callback() #4 /mnt/c/htdocs/yellow-master/system/extensions/markdown.php(3879): preg_replace_callback() #5 /mnt/c/htdocs/yellow-master/system/extensions/markdown.php(669): YellowMarkdownParser->doAutoLinks() #6 /mnt/c/htdocs/yellow-master/system/extensions/markdown.php(3518): MarkdownParser->runSpanGamut() #7 /mnt/c/htdocs/yellow-master/system/extensions/markdown.php(613): MarkdownExtraParser->formParagraphs() #8 /mnt/c/htdocs/yellow-master/system/extensions/markdown.php(299): MarkdownParser->runBasicBlockGam in /mnt/c/htdocs/yellow-master/system/extensions/csv.php on line 88`

Can you have a look?

Thx, 

Carsten / JetGum

**Comment by schulle4u** [comment]
Thanks Carsten, I've fixed the bug. Recently we had some API changes, and I missed one of them while updating my extensions.

**Comment by JetGum** [comment]
So quick, great! I can confirm that it works.
